language: c

sudo: required

services:
  - docker

env:
  global:
    # FTP_USER
    - secure: "kaPQI+ky7ARW+B42aLIS6VIr/C7SqCIs7UDM3/j5IkZlUmX7arg18q3j0/EqudJCm8+jynyMsltMq/L3yi5crZwsWpCTqTbYLQqx14k91P/MJTuv9F2V+dS/DPINNK/1vM26oFNiD3XlIJ14tiF7lXkLY5PHfD3zq/Exu1aa5F+/dZYTph6hui89osHHJ/5MzwYELif/+Xk7SFw+DUf6/MmLKYhAbYQvnyisCbCxanImp0IXRt0G+3fDLuGCCxpFbklFyzCFp6fHGHdXKo6oTEUsnmNSEXWRX4Ntkr9bYsKlXu8XN83UovqLM527ksYk+K5/EMP6BYZfE2Kw8OovNfcXHVE7lr6nSFt5UK7SZyT/27ra+Ds3lHadTgr8BU2s1s2d+7aGRMbca/BGCdJteltupUD2LIcBKrj0AOPBxAXX5dKX4LW/hJQUYA+nuXJu2/6TdRRnyfDyXBQ1dh2ZtfR6+HhDPSfSnDK9IbZ5ZzLwAiOAp0qpGn4By2Ouul6dYa+ALH7+37cC+RB9PkpNu04VQAYSp3tNPaHMLQkz561/ECtDAtlFx+MtLDx3quPVCmw7798CUq28oMr/Ni+eagp03Kacu/fFf9uxBYtNQeuh7MsE9ODGkkU60yLIUvLQWAyeNZSroLdJor/kkieEPsXHo4Yc7NEi9UMTZFGftP0="
    # FTP_PASSWORD
    - secure: "iyXPguBqEPlCSPBZ/OtAnNIOzoIwQwKGKNem4PMJUXsmawlDxq4Dj0lDApucz/RIfoWwOsj2sm5Afb7Fz4tCG8dyAJYVEJTQKm36PiT8oEMR/+KLyueGnR7j/N5aLStKO9Mc2i4MJZyB/7y9DDS+NPmKCqzAKLiIxxagzpe4XRNiMDn2yykR1otvPV18fQwuDVvY+i3kKed2jHxqLFM5RG+1ZWs6wJ6nGT4hpEGN5DzTgdjW70pdDmG8X7fHuaQzjIioB4T/opRdZF6rkdLS009wKGfhMd1luucbTlzvHm+mgA9//ejZB3xZEOVB/G7XheWN1cPF7nIgLNOznSnilJfET27KAfy7/2l9L/0cM1NB6ZQNjUMjR1ddhICwWtf/BPM033j8GdMLlT9TX9xLjYpQ20OgMQpS298JIMPrwFE4/vnwc7p8q2uxrCctk7hBlP7mYKIoNbiTTsGl0xA8toeG/UPiduc0lWr3u5zKNj+nNhUcGNPMAQsO3yXnfAANgVFuTlJn5fKPb8u3QPfyYG+XS0xRXyne5oy8VEkaAHTb3TQZ78k7rv0VhZGhgCeMmEuqydigHjT7s+9oUTVHD8Vtjjut0OEWzH7bJpNjp8wQVonFY9BwsTgWNGHXu8+/ECH/0XGypYAA2s7iV8pyjuKgd0+qMEtZjD17t6KrXzQ="
    # FTP_URL
    - secure: "HtM+gpjvbJ1tnpWWc7jWTUuzf2+AYA7HPriH1hsQmm8HKDXMioYA8wRKdLVHN55MADoXtb+M9oons8RQ/oZ6WLDRR9x4LXFucvi7kamS66sR47S2fY2j4AcRsHmM/0fAHQWyOL7XdokGmg6bPo2ze3lyuI1veJH6qAWTyljeVrKvaLqAbKLRCg0eD5qpS91G1lTenv2t5cmeUIbB3PoWUZSdCWKx9aoAUxoeroyN5MMR7Q4F4loEZ+CoqqDK2nlS0ah4qzmiM6HG2vGK2IHjduL48eMg7zUMFUyj3TEdd1/lOxNyWb1BZc9xLhCGYMGmtZqhOtXSScx0AHb5ojDcFEGXWz1eDgDzzutmAz/JyLE9hIDnCXasn42Av3qrkIJlbbEmPByy4b4vn62P3KstDVYQVtOHepJYNHQpMkrnh9tH8I83UDz+nNkpXx8HEOBfvKUqeMjn41rhfG+AG9iTAJxWOeKZDJ5Lv38/1KR51sC6qBiKGwegUYHxc+X4cmKTOofMZWj07JMfc+oeXg6/ZKF3EsFkIYKk8dPkTRr7ZY4CCL/YvPyoQlLKYRRinBBy8m8SQ0f9PtJa5OhPGGkqNTgHbV/lfOVgslb4/jolO0GmmQImjgTpwqeOTw/ZKfShVDg02tnoGd86L4oHB/+TE0LMo97yY60xrz5BDMdYX28="

arch:
  artifacts:
    - qbs-shared-artifacts.tar.gz
  packages:
    - qbs
  script:
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - qbs build -d build -j $(nproc) profile:qt5 modules.lirideployment.prefix:/usr

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
